### ISSUE TITLE
Remove ability for users to bookmark, email, sms, or cite record

### ISSUE THREAD

**Issue by jessemartinez** [BCDigSchol/jesuit-lives#27]
**Is your feature request related to a problem? Please describe.**
Since we're not allowing the public to create accounts we should remove the ability to do certain tasks dependent on being signed in like bookmark, email, sms. Likewise, we're not using the citation feature so this should also be removed. 

**Describe the solution you'd like**
Deactivate those features from the Blacklight cataloging controller config.

**Comment by Otterfan** [comment]
Closed with f82e33f68d0351da2229e8b5f0337fde2ea6155b
